steps:

# Backend / Build Docker container
- name: docker:20.10
  id: 'backend-test'
  args: ['build', '-t', 
          'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', './backend',
          '--target=test']
  env:
  - 'DOCKER_BUILDKIT=1'

# Frontend / Install dependencies
- name: node:16.10
  id: 'frontend-init'
  entrypoint: npm
  args: ['install']
  dir: 'frontend/'
  waitFor: ['-']

# Frontend / Build
- name: node:16.10
  id: 'frontend-build'
  entrypoint: npm
  args: ['run', 'build']
  env:
  - 'WORDBREW_API_URL=${_WORDBREW_API_URL}'
  dir: 'frontend/'
  waitFor: ['frontend-init']

substitutions:
    _WORDBREW_API_URL: https://wordbrew-api-q35ri6rwla-wl.a.run.app
