steps:
# --- Backend ---
# Build Docker container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
          'gcr.io/$PROJECT_ID/wordbrew:$BUILD_ID', './backend']

# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/wordbrew:$BUILD_ID']

# Deploy to Cloud Run
- name: google/cloud-sdk
  args: ['gcloud', 'run', 'deploy', 'wordbrew-api', 
          '--image=gcr.io/$PROJECT_ID/wordbrew:$BUILD_ID', 
          '--region', 'us-west2', '--platform', 'managed', 
          '--allow-unauthenticated', '--port', '8000']

# --- Frontend ---
# Install dependencies
- name: node:16.10
  entrypoint: npm
  args: ['install']
  dir: 'frontend/'

# Build
- name: node:16.10
  entrypoint: npm
  args: ['run', 'build']
  env:
  - 'WORDBREW_API_URL=${_WORDBREW_API_URL}'
  dir: 'frontend/'

# Sync to storage bucket
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gsutil
  args: ['-m', 'rsync', '-r', '-d', './frontend/build', 'gs://${_BUCKET_NAME}']

# Set no cache on index.html
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gsutil
  args: ['setmeta', '-h', 'Cache-Control:no-store', 'gs://${_BUCKET_NAME}/index.html']

substitutions:
    _WORDBREW_API_URL: https://wordbrew-api-q35ri6rwla-wl.a.run.app
    _BUCKET_NAME: wordbrew.io
