version: '3.4'
services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:r
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:r
      - node-modules:/app/node_modules
    environment:
      - WORDBREW_API_URL=http://localhost:8000
    command: npm start
    restart: on-failure

volumes:
  node-modules:
