version: '3.4'
services:

  backend:
    build:
      context: ./backend
      target: base
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:r
  
  frontend:
    build: 
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:r
      - node-modules:/app/node_modules
    restart: on-failure

volumes:
  node-modules:
