version: '3.4'
services:

  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:r
    container_name: wordbrew_backend
  
  frontend:
    build: 
      context: ./frontend
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app:r
    restart: on-failure
